export const vessels = [
  'CMA-CGM-CONCORDE',
  'CMA-CGM-JEAN-MERMOZ',
  'COSCO-SHIPPING-GALAXY',
  'COSCO-SHIPPING-GEMINI',
  'EVER-GENIUS',
  'EVER-GENTLE',
  'HMM-COPENHAGEN',
  'HMM-DUBLIN',
  'MARSEILLE-MAERSK',
  'MONACO-MAERSK',
  'OOCL-GERMANY',
  'OOCL-INDONESIA',
]
